import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const htmlPath = path.join(root, 'ref/ui-based-converter/sulekh_to_unicode_7.html');
const html = fs.readFileSync(htmlPath, 'utf8');

function extractArrayAfterMarker(marker) {
  const fnStart = html.indexOf(marker);
  if (fnStart === -1) throw new Error(`Marker not found: ${marker}`);
  const arrStart = html.indexOf('var array_one = new Array(', fnStart);
  const arrEnd = html.indexOf('var array_one_length = array_one.length;', arrStart);
  const snippet = html.substring(arrStart, arrEnd);
  return new Function(`${snippet} return array_one;`)();
}

function writeMapFile(outPath, exportName, array) {
  const content = `// Generated by scripts/extract-maps.js\nexport const ${exportName} = ${JSON.stringify(array)};\n`;
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, content, 'utf8');
}

const sulekhToUnicodeMap = extractArrayAfterMarker('function convert_to_unicode()');
const unicodeToSulekhMap = extractArrayAfterMarker('function Convert_Unicode_to_Guj_Regular_SULEKH()');
writeMapFile(path.join(root, 'src/converter/maps/sulekhToUnicode.map.js'), 'SULEKH_TO_UNICODE_MAP', sulekhToUnicodeMap);
writeMapFile(path.join(root, 'src/converter/maps/unicodeToSulekh.map.js'), 'UNICODE_TO_SULEKH_MAP', unicodeToSulekhMap);
console.log('maps ok', sulekhToUnicodeMap.length, unicodeToSulekhMap.length);
